[package]
name = "rustboard-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
rustboard-editor = { path = "../../editor" }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
